#!/bin/bash

INTERFACE="eth0"          
IP_ALVO="203.0.113.5"     
PORTA="50051"             
ARQUIVO_SAIDA="/tmp/capture.pcap"

echo "Iniciando captura na interface ${INTERFACE}..."
echo "Filtrando: IP ${IP_ALVO}, porta ${PORTA}, protocolo TCP"
echo "Arquivo de saída: ${ARQUIVO_SAIDA}"

sudo tcpdump -i "${INTERFACE}" -s 0 -w "${ARQUIVO_SAIDA}" "tcp and host ${IP_ALVO} and port ${PORTA}"